# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site Settings
title: "Design&Tech Salamanca 2014"
email: "info@gdgsalamanca.com"
description: "Design&Tech Salamanca es el evento de difusión del diseño y la tecnología en Salamanca"
baseurl: "/zeppelin"
url: "http://juan-cb.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Salamanca"
organizerAlternateName: "Google Developer Group Salamanca"
organizerDescription: "¡Hablamos de tecnología, creamos Comunidad!"
organizerEmail: "info@gdgsalamanca.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgsalamanca.com"

# Head
metaKeywords: "event, gdg, design&tech, google, design, betabeers, diseño, evento, salamanca, charrosfera, tecnología"
twitterAccount: "@gdgsalamanca"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/agenda/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/organizadores/", text: "Organizadores"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "http://bit.ly/dfua-c4p", text: "Regístrate"}
rightNavigationButtons:
 - {link: "http://bit.ly/dfua-c4p", text: "Regístrate"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Design&Tech <typeout> 2014"
eventDate: "29 Noviembre 2014"
typeoutTextValues: '"", "Salamanca"'
typeoutFallback: "Salamanca"
heroButtons:
 - {link: "/agenda/", text: "Agenda"}
 - {permalink: "/#tickets", text: "Regístrate"}

# About Block
aboutTitle: "Design&Tech Salamanca 2014"
aboutBlock:
 - {title: "¿Por qué?", image: "conference.jpg", text: "Queremos hablar de diseño y tecnología. Queremos promocionar el diseño en Salamanca" }
 - {title: "¿Cómo?", image: "workshop.jpg", text: "Hemos organizado un evento con ponencias de gran calidad, y con un tiempo para networking. Conoce más sobre el diseño y tecnología y busca diseñadores con los que trabajar" }
 - {title: "¿Dónde?", image: "hackathon.jpg", text: "En la Facultad de Ciencias de la Universidad de Salamanca" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "50", specialCharacter: "+", info: "asistentes", detail: "de cualquier lugar"}
 - {count: "5", specialCharacter: "+", info: "horas", detail: "hablando sobre diseño/tecnología y haciendo networking"}
 - {count: "5", specialCharacter: "", info: "speakers", detail: "tanto de Salamanca como de otras ciudades"}
# - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Últimas noticias"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "Más información"

# Location Block
locationBlockTitle: "¿Dónde?"
eventLocationName: "Salón de actos de la Facultad de Ciencias de la Universidad de Salamanca"
eventLocationLink: "http://fciencias.usal.es"
eventStreetAddress: "Plaza de los Caídos s/n"
eventAddressLocality: "Salamanca"
eventAddressLocalityRegion: "Salamanca"
eventPostalCode: "37008"
eventAddressCountry: "España"
eventStartTime: "2014-11-29T10:00"
eventDoorTime: "09:30"
eventEndTime: "2014-10-29T14:00"
eventPlaceCoordinates: "40.9634385, -5.6692121"
mapCenterCoordinates: "40.9634385, -5.6692121"
mapMobileCenterCoordinates: "40.9634385, -5.6692121"

# Venue Block
#venueBlockTitle: "Venue"
#venueBigImage: "venue_0.jpg"
#venueSmallImage1: "venue_1.jpg"
#venueSmallImage2: "venue_2.jpg"
#venueSmallImage3: "venue_3.jpg"
#venueTitle: "Kinopalace Cinema"
#venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "¿Qué dice la gente?"
twitterHashTag: "designtechSAL14"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "¿Quieres ser patrocinador?"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Suscríbete para recibir más noticias"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Te informaremos sobre las novedades del evento y cualquier noticia relacionada"

# Tickets Block
ticketsTitle: "Regístrate"
ticketsInfo: "Es gratis, pero necesitamos que te registres para saber quién va a venir"
ticketsOffers:
 -
  name: "Registro normal"
  price: "0"
  priceCurrency: "EUROS"
  ticketsNumber: "150"
 # ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Regístrate"
  ticketContentList: ["¡Ven al evento!"]
  validFrom: "2014-10-29T10:00"
  validThrough: "2014-11-29T23:59"
# -
#  name: "Last Chance"
#  price: "450"
#  priceCurrency: "UAH"
#  ticketsNumber: "100"
#  ribbon: "-20%"
#  featured: true
#  buyButtonLink: "http://dfua.ticketforevent.com/"
#  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-10-01T00:00"
#  validThrough: "2014-10-23T23:59"
#  disabled: true
# -
#  name: "Student"
#  price: "200"
#  priceCurrency: "UAH"
#  ticketsNumber: "50"
#  buyButtonLink: "http://dfua.ticketforevent.com/"
#  buyButtonText: "Buy Now"
#  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-20T10:00"
#  validThrough: "2014-10-23T23:59"
#  soldOut: true
#  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/107931642576280918674", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGSalamanca", icon: "twitter"}
 - {link: "https://facebook.com/GDGSalamanca", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdgsalamanca.com", text: "GDG Salamanca"}
   - {link: "http://betabeers.com", text: "Betabeers Salamanca"}
   - {link: "http://charrosfera.com", text: "Charrosfera"} 
   - {link: "http://usal.es", text: "Universidad de Salamanca"}
 -
  title: "Contacto"
  links:
   - {link: "mailto:info@gdgsalamanca.com", text: "info@gdgsalamanca.com"}
# -
#  title: "FAQ"
#  links:
#   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Últimas noticias"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "¿Quiénes somos?"
aboutUs: "Creamos comunidad en Salamanca sobre tecnología. Montamos eventos. Hablamos de Cosas. Hacemos Cosas. Conócenos"

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards: 
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   - 
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
#hackathonTitle: "Hackathon"
#enableHackathon: true

# Hackathon About Block
#aboutHackathonTitle: "Meet our themes"
#hackathonRows:
# - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
# - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
# - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
#judgesImage: "judges.jpg"
#judgesTitle: "Judges"

# Hackathon Prizes Block
#prizesTitle: "Prizes"
#prizes:
# - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
# - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
# - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
#hackathonLocationBlockTitle: "Location"
#hackathonLocationName: "Communa"
#hackathonLocationLink: "http://communa.net.ua/"
#hackathonStreetAddress: "1 Halytska St"
#hackathonAddressLocality: "Lviv"
#hackathonAddressLocalityRegion: "Lvivska"
#hackathonPostalCode: "79000"
#hackathonAddressCountry: "Ukraine"
#hackathonTimeTitle: "Hack through"
#hackathonStartTime: "2014-10-24T10:00"
#hackathonDoorTime: "09:00"
#hackathonEndTime: "2014-10-25T00:00"
#viewOnMap: "View on Google Maps"
#hackathonPlaceCoordinates: "49.840999, 24.031144"
#hackathonMapCenterCoordinates: "49.840696, 24.028754"
#hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"